name: anah_luxury
description: A new Flutter project.  
publish_to: 'none'   

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  go_router: ^6.5.6
  shimmer: ^2.0.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf

  # fonts:
  #   - family: Pacifico
  #     fonts:
  #       - asset: fonts/Pacifico.ttf
  #   - family: Inter
  #     fonts:
  #       - asset: fonts/Inter-Regular.tff
    
  assets:
    - assets/
    - assets/welcome_page/
    - assets/login/
    - assets/home_page/
    - assets/bottom_bar/

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: assets.dart
    

    
    

    
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
